<a href="https://colab.research.google.com/github/Ashubapun/Heart-Disease-Prediction/blob/main/Heart_Disease_Prediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Importing Libraries

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns
import plotly.express as px

In [2]:
# Libraries for classifications
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.linear_model import LogisticRegression

In [3]:
# Reading Dataset
df = pd.read_csv('/content/framingham.csv')
df

male  age  education  currentSmoker  cigsPerDay  BPMeds  \
0        1   39        4.0              0         0.0     0.0   
1        0   46        2.0              0         0.0     0.0   
2        1   48        1.0              1        20.0     0.0   
3        0   61        3.0              1        30.0     0.0   
4        0   46        3.0              1        23.0     0.0   
...    ...  ...        ...            ...         ...     ...   
4235     0   48        2.0              1        20.0     NaN   
4236     0   44        1.0              1        15.0     0.0   
4237     0   52        2.0              0         0.0     0.0   
4238     1   40        3.0              0         0.0     0.0   
4239     0   39        3.0              1        30.0     0.0   

      prevalentStroke  prevalentHyp  diabetes  totChol  sysBP  diaBP    BMI  \
0                   0             0         0    195.0  106.0   70.0  26.97   
1                   0             0         0    250.0  121.0   81.0  28.73   
2                   0             0         0    245.0  127.5   80.0  25.34   
3                   0             1         0    225.0  150.0   95.0  28.58   
4                   0             0         0    285.0  130.0   84.0  23.10   
...               ...           ...       ...      ...    ...    ...    ...   
4235                0             0         0    248.0  131.0   72.0  22.00   
4236                0             0         0    210.0  126.5   87.0  19.16   
4237                0             0         0    269.0  133.5   83.0  21.47   
4238                0             1         0    185.0  141.0   98.0  25.60   
4239                0             0         0    196.0  133.0   86.0  20.91   

      heartRate  glucose  TenYearCHD  
0          80.0     77.0           0  
1          95.0     76.0           0  
2          75.0     70.0           0  
3          65.0    103.0           1  
4          85.0     85.0           0  
...         ...      ...         ...  
4235       84.0     86.0           0  
4236       86.0      NaN           0  
4237       80.0    107.0           0  
4238       67.0     72.0           0  
4239       85.0     80.0           0  

[4240 rows x 16 columns]

In [4]:
df['TenYearCHD'].value_counts()

0    3596
1     644
Name: TenYearCHD, dtype: int64

In [5]:
df['male'].value_counts()

0    2420
1    1820
Name: male, dtype: int64

In [6]:
df['diabetes'].value_counts()

0    4131
1     109
Name: diabetes, dtype: int64

In [7]:
df.duplicated().sum()

0

In [8]:
df.isnull().sum()

male                 0
age                  0
education          105
currentSmoker        0
cigsPerDay          29
BPMeds              53
prevalentStroke      0
prevalentHyp         0
diabetes             0
totChol             50
sysBP                0
diaBP                0
BMI                 19
heartRate            1
glucose            388
TenYearCHD           0
dtype: int64

In [9]:
df['education'].value_counts()

1.0    1720
2.0    1253
3.0     689
4.0     473
Name: education, dtype: int64

In [10]:
df[df['education'].isnull()]

male  age  education  currentSmoker  cigsPerDay  BPMeds  \
33       1   61        NaN              1         5.0     0.0   
36       1   56        NaN              0         0.0     0.0   
72       0   37        NaN              0         0.0     0.0   
184      1   67        NaN              0         0.0     0.0   
213      0   34        NaN              0         0.0     0.0   
...    ...  ...        ...            ...         ...     ...   
4082     1   47        NaN              0         0.0     0.0   
4098     1   37        NaN              1        20.0     0.0   
4121     0   55        NaN              0         0.0     0.0   
4122     1   69        NaN              1        23.0     0.0   
4138     1   67        NaN              1        25.0     0.0   

      prevalentStroke  prevalentHyp  diabetes  totChol  sysBP  diaBP    BMI  \
33                  0             0         0    175.0  134.0   82.5  18.59   
36                  0             0         0    257.0  153.5  102.0  28.09   
72                  0             0         0    200.0  119.0   79.0  33.29   
184                 0             0         0    257.0  125.0   67.5  25.95   
213                 0             0         0    163.0  107.0   71.0  23.88   
...               ...           ...       ...      ...    ...    ...    ...   
4082                0             1         0    254.0  137.5   91.0  31.98   
4098                0             0         0    184.0  113.0   81.0  22.16   
4121                0             0         0    240.0  145.0   96.0  26.27   
4122                0             1         0    186.0  179.0   93.0  26.64   
4138                0             1         0    221.0  144.0   84.0  24.92   

      heartRate  glucose  TenYearCHD  
33         72.0     75.0           1  
36         72.0     75.0           0  
72         67.0     87.0           0  
184        65.0     69.0           0  
213        73.0     80.0           0  
...         ...      ...         ...  
4082       75.0     69.0           0  
4098       85.0     63.0           0  
4121       72.0      NaN           0  
4122       72.0     67.0           0  
4138       72.0     73.0           0  

[105 rows x 16 columns]

In [11]:
df['BPMeds'].value_counts()

0.0    4063
1.0     124
Name: BPMeds, dtype: int64

In [12]:
df[df['BPMeds'].isnull()]

male  age  education  currentSmoker  cigsPerDay  BPMeds  \
49       1   36        3.0              1        20.0     NaN   
77       0   44        3.0              1        20.0     NaN   
193      1   45        3.0              1        40.0     NaN   
245      1   46        1.0              1        30.0     NaN   
314      0   39        2.0              0         0.0     NaN   
395      0   65        2.0              0         0.0     NaN   
421      1   44        1.0              0         0.0     NaN   
765      1   50        4.0              1         9.0     NaN   
769      0   37        3.0              0         0.0     NaN   
797      0   59        4.0              0         0.0     NaN   
998      0   57        1.0              0         0.0     NaN   
1002     1   60        1.0              0         0.0     NaN   
1044     0   65        1.0              0         0.0     NaN   
1104     1   57        4.0              0         0.0     NaN   
1122     0   67        1.0              1         6.0     NaN   
1177     0   55        1.0              0         0.0     NaN   
1206     0   66        1.0              0         0.0     NaN   
1284     1   41        1.0              1        15.0     NaN   
1301     0   43        3.0              1        10.0     NaN   
1566     1   58        1.0              1        30.0     NaN   
1573     0   67        2.0              0         0.0     NaN   
1616     0   41        1.0              0         0.0     NaN   
1721     0   57        1.0              0         0.0     NaN   
1857     1   56        1.0              1        20.0     NaN   
1861     0   60        1.0              0         0.0     NaN   
1913     1   51        1.0              0         0.0     NaN   
1983     0   63        2.0              0         0.0     NaN   
1985     0   59        1.0              1         3.0     NaN   
1986     0   59        1.0              1        30.0     NaN   
2002     0   59        1.0              1        20.0     NaN   
2074     1   45        2.0              1        10.0     NaN   
2120     0   61        1.0              0         0.0     NaN   
2173     0   62        3.0              0         0.0     NaN   
2181     0   56        1.0              1         9.0     NaN   
2367     0   57        4.0              0         0.0     NaN   
2608     0   52        1.0              0         0.0     NaN   
2645     0   66        1.0              0         0.0     NaN   
2738     0   68        1.0              0         0.0     NaN   
2835     0   40        1.0              1        50.0     NaN   
2943     0   56        2.0              0         0.0     NaN   
3226     0   41        1.0              1        20.0     NaN   
3313     0   52        3.0              1         9.0     NaN   
3373     1   51        4.0              0         0.0     NaN   
3375     0   68        2.0              0         0.0     NaN   
3526     0   60        1.0              0         0.0     NaN   
3644     1   55        1.0              1         3.0     NaN   
3737     0   41        2.0              1        20.0     NaN   
3791     1   54        4.0              1        30.0     NaN   
3816     0   56        1.0              0         0.0     NaN   
4008     0   40        2.0              0         0.0     NaN   
4139     0   53        3.0              0         0.0     NaN   
4162     0   47        3.0              1         9.0     NaN   
4235     0   48        2.0              1        20.0     NaN   

      prevalentStroke  prevalentHyp  diabetes  totChol  sysBP  diaBP    BMI  \
49                  0             1         0    194.0  139.0   93.0  24.33   
77                  0             0         0    213.0  115.0   72.5  21.16   
193                 0             0         0    278.0  135.0   84.0  23.79   
245                 0             1         0    253.0  147.0   85.0  30.62   
314                 0             0         0    242.0  113.0   85.0  25.54   
395                 0

In [13]:
new_df = df.dropna()

In [14]:
new_df.shape

(3658, 16)

In [15]:
new_df

male  age  education  currentSmoker  cigsPerDay  BPMeds  \
0        1   39        4.0              0         0.0     0.0   
1        0   46        2.0              0         0.0     0.0   
2        1   48        1.0              1        20.0     0.0   
3        0   61        3.0              1        30.0     0.0   
4        0   46        3.0              1        23.0     0.0   
...    ...  ...        ...            ...         ...     ...   
4233     1   50        1.0              1         1.0     0.0   
4234     1   51        3.0              1        43.0     0.0   
4237     0   52        2.0              0         0.0     0.0   
4238     1   40        3.0              0         0.0     0.0   
4239     0   39        3.0              1        30.0     0.0   

      prevalentStroke  prevalentHyp  diabetes  totChol  sysBP  diaBP    BMI  \
0                   0             0         0    195.0  106.0   70.0  26.97   
1                   0             0         0    250.0  121.0   81.0  28.73   
2                   0             0         0    245.0  127.5   80.0  25.34   
3                   0             1         0    225.0  150.0   95.0  28.58   
4                   0             0         0    285.0  130.0   84.0  23.10   
...               ...           ...       ...      ...    ...    ...    ...   
4233                0             1         0    313.0  179.0   92.0  25.97   
4234                0             0         0    207.0  126.5   80.0  19.71   
4237                0             0         0    269.0  133.5   83.0  21.47   
4238                0             1         0    185.0  141.0   98.0  25.60   
4239                0             0         0    196.0  133.0   86.0  20.91   

      heartRate  glucose  TenYearCHD  
0          80.0     77.0           0  
1          95.0     76.0           0  
2          75.0     70.0           0  
3          65.0    103.0           1  
4          85.0     85.0           0  
...         ...      ...         ...  
4233       66.0     86.0           1  
4234       65.0     68.0           0  
4237       80.0    107.0           0  
4238       67.0     72.0           0  
4239       85.0     80.0           0  

[3658 rows x 16 columns]

In [16]:
new_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 3658 entries, 0 to 4239
Data columns (total 16 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   male             3658 non-null   int64  
 1   age              3658 non-null   int64  
 2   education        3658 non-null   float64
 3   currentSmoker    3658 non-null   int64  
 4   cigsPerDay       3658 non-null   float64
 5   BPMeds           3658 non-null   float64
 6   prevalentStroke  3658 non-null   int64  
 7   prevalentHyp     3658 non-null   int64  
 8   diabetes         3658 non-null   int64  
 9   totChol          3658 non-null   float64
 10  sysBP            3658 non-null   float64
 11  diaBP            3658 non-null   float64
 12  BMI              3658 non-null   float64
 13  heartRate        3658 non-null   float64
 14  glucose          3658 non-null   float64
 15  TenYearCHD       3658 non-null   int64  
dtypes: float64(9), int64(7)
memory usage: 485.8 KB


In [17]:
new_df = new_df.rename(columns = {'TenYearCHD' : 'Y'})

In [18]:
new_df['Y'].value_counts()

0    3101
1     557
Name: Y, dtype: int64

In [19]:
x = new_df.drop(columns = 'Y')
y = new_df['Y']

In [20]:
# resampling
from imblearn.over_sampling import RandomOverSampler
ros = RandomOverSampler(sampling_strategy='minority')
x,y = ros.fit_resample(x,y)

In [21]:
x.shape

(6202, 15)

In [22]:
y.shape

(6202,)

In [23]:
# train_test_split
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.25, random_state = 42)

In [24]:
x_train.shape, y_train.shape

((4651, 15), (4651,))

In [25]:
x_test.shape, y_test.shape

((1551, 15), (1551,))

In [26]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
x_train = scaler.fit_transform(x_train)
x_test = scaler.fit_transform(x_test)

In [27]:
# modeling
# KNN
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=2)
knn.fit(x_train,y_train)
y_pred = knn.predict(x_test)

In [28]:
y_pred

array([1, 0, 0, ..., 1, 0, 0])

In [29]:
from sklearn.metrics import accuracy_score , confusion_matrix
score = accuracy_score(y_test, y_pred)
cm = confusion_matrix(y_test, y_pred)
score, cm

(0.8994197292069632,
 array([[660, 119],
        [ 37, 735]]))

In [30]:
# cross-validation
from sklearn.model_selection import cross_val_score
cvs = cross_val_score(estimator = knn, X = x_train, y = y_train, cv = 10)
cvs.mean()

0.8847528727675481

In [31]:
# logistic regression
from sklearn.linear_model import LogisticRegression
lr = LogisticRegression(max_iter=2000)          ## penalty = 'elasticnet', max_iter=1000, solver = 'saga'
lr.fit(x_train,y_train)
y_pred1 = lr.predict(x_test)

score1 = accuracy_score(y_test, y_pred1)
cm1 = confusion_matrix(y_test, y_pred1)

cvs1 = cross_val_score(estimator = lr, X = x_train, y = y_train, cv = 10)
score1, cm1, cvs1.mean()

(0.6866537717601547,
 array([[532, 247],
        [239, 533]]),
 0.6697489501130648)

In [32]:
# svm classifier
from sklearn.svm import SVC
sv = SVC()
sv.fit(x_train,y_train)
y_pred2 = lr.predict(x_test)

score2 = accuracy_score(y_test, y_pred2)
cm2 = confusion_matrix(y_test, y_pred2)

cvs2 = cross_val_score(estimator = sv, X = x_train, y = y_train, cv = 10)
score2, cm2, cvs2.mean()

(0.6866537717601547,
 array([[532, 247],
        [239, 533]]),
 0.7035045456643131)

In [33]:
# Decision Tree
from sklearn.tree import DecisionTreeClassifier
dt = DecisionTreeClassifier(criterion= 'gini')
dt.fit(x_train,y_train)
y_pred3 = lr.predict(x_test)

score3= accuracy_score(y_test, y_pred3)
cm3 = confusion_matrix(y_test, y_pred3)

cvs3 = cross_val_score(estimator = dt, X = x_train, y = y_train, cv = 10)
score3, cm3, cvs3.mean()

(0.6866537717601547,
 array([[532, 247],
        [239, 533]]),
 0.9021694586736813)

In [34]:
# Random Forest
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier(n_estimators=150)
rf.fit(x_train,y_train)
y_pred4 = lr.predict(x_test)

score4 = accuracy_score(y_test, y_pred4)
cm4 = confusion_matrix(y_test, y_pred4)

cvs4 = cross_val_score(estimator = rf, X = x_train, y = y_train, cv = 10)
score4, cm4, cvs4.mean()

(0.6866537717601547,
 array([[532, 247],
        [239, 533]]),
 0.958500161521067)

In [35]:
# Perceptron
from sklearn.linear_model import Perceptron
percept = Perceptron(alpha = 0.001)
percept.fit(x_train,y_train)
y_pred5 = lr.predict(x_test)

score5 = accuracy_score(y_test, y_pred5)
cm5 = confusion_matrix(y_test, y_pred5)

cvs5 = cross_val_score(estimator = percept, X = x_train, y = y_train, cv = 10)
score5, cm5, cvs5.mean()

(0.6866537717601547,
 array([[532, 247],
        [239, 533]]),
 0.5897711015736766)

In [36]:
# XGBoost
from sklearn.ensemble import GradientBoostingClassifier
xgb = GradientBoostingClassifier(n_estimators=100, learning_rate=1.0, max_depth=1, random_state=0)
xgb.fit(x_train, y_train)
y_pred6 = xgb.predict(x_test)

score6 = accuracy_score(y_test, y_pred5)
cm6 = confusion_matrix(y_test, y_pred5)

cvs6 = cross_val_score(estimator = xgb, X = x_train, y = y_train, cv = 10)
score6, cm6, cvs6.mean()

(0.6866537717601547,
 array([[532, 247],
        [239, 533]]),
 0.6841510914209238)